// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/14/2025, 9:09:49 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/vili/Documents/web_projekti/proba/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vili/Documents/web_projekti/proba/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vili/Documents/web_projekti/proba/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vili/Documents/web_projekti/proba/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vili/Documents/web_projekti/proba/plugins/**/*.{js,ts,mjs}","/home/vili/Documents/web_projekti/proba/composables/**/*.{js,ts,mjs}","/home/vili/Documents/web_projekti/proba/utils/**/*.{js,ts,mjs}","/home/vili/Documents/web_projekti/proba/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vili/Documents/web_projekti/proba/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/vili/Documents/web_projekti/proba/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/vili/Documents/web_projekti/proba/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;